name: "Workflow Commands"
on:
  - push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: "group logging"
        run: | 
          echo "::group::My Group Message"
          echo "Msg 1"
          echo "Msg 2"
          echo "::endgroup::"